---
- hosts: all
  roles:
    - apt
    - ufw
    - git
  tasks:
    - name: "os : 'max_user_watches' is set to 524288"
      become: yes
      lineinfile:
        path: "/etc/sysctl.conf"
        line: "fs.inotify.max_user_watches=524288"
      notify:
        - configure max_user_watches
  handlers:
    - name: configure max_user_watches
      become: yes
      command: sysctl -p
