---
- hosts: all
  tasks:
    - name: "apt : nodejs gpg key is present"
      become: "true"
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        id: "68576280"
        state: present
    - name: "apt : nodejs 14 lts repository is present"
      become: "true"
      ansible.builtin.apt_repository:
        repo: deb https://deb.nodesource.com/node_14.x focal main
        state: present
    - name: "apt : nodejs 14 lts repository is present"
      become: "true"
      ansible.builtin.apt_repository:
        repo: deb-src https://deb.nodesource.com/node_14.x focal main
        state: present
    - name: "apt : packages are up to date"
      become: "true"
      apt:
        upgrade: "yes"
        update_cache: "yes"
    - name: "apt : required packages are present"
      become: yes
      apt:
        pkg:
          - nodejs
          - npm
        state: present
    - name: "npm : global directory is present"
      file:
        path: "~/.npm-global"
        owner: "{{ ansible_user }}"
        state: directory
        mode: 0755
      notify:
        - configure npm global
    - name: "os : npm packages in PATH"
      lineinfile:
        path: "~/.profile"
        line: "export PATH=~/.npm-global/bin:$PATH"
        create: yes
  handlers:
    - name: configure npm global
      command: npm config set prefix '~/.npm-global'
