- name: required packages are installed
  become: yes
  apt:
    pkg:
      - apache2
      - php
    state: present

- name: apache2 service is active
  become: yes
  service:
    name: apache2
    state: started

- name: apache2 rewrite module is enabled
  become: yes
  apache2_module:
    name: rewrite
    state: present
  notify:
    - restart apache2

- name: set default apache2 config source
  set_fact:
    apache2_config_path: "example.apache2.conf"
  when: apache2_config_path is not defined # only if not custom mysql_config path

- name: apache2 server is configured
  become: yes
  copy:
    src: "{{ playbook_dir }}/config/{{ apache2_config_path }}"
    remote_src: no
    dest: "/etc/apache2/apache2.conf"
  notify:
    - restart apache2

- name: "group 'www' is present"
  become: yes
  group:
    name: www
    state: present

- name: "'{{ host_user }}' is in 'www' group"
  become: yes
  user:
    name: "{{ host_user }}"
    groups: www
    append: yes

- name: "'root' is part of 'www' group"
  become: yes
  user:
    name: root
    groups: www
    append: yes

- name: "dir '/var/www/html' is owned by 'www' group"
  become: yes
  file:
    path: /var/www/html
    group: www
    mode: "0775"

- name: "symlink to 'html' at '{{ host_user }}'' directory is present"
  become: yes
  file:
    src: "/var/www/html"
    dest: "/home/{{ host_user }}/HTML"
    state: link

- name: ufw http is allowed
  become: yes
  ufw:
    rule: allow
    port: "80"
    proto: tcp
  when: wsl_mode is not defined # skip when wsl_mode
  notify:
    - enable ufw
