- name: packages are up to date
  become: "true"
  apt:
    upgrade: "yes"
    update_cache: "yes"

- name: basic packages are present
  become: yes
  apt:
    pkg:
      - wget
      - htop
      - tmux
    state: present
