- name: git user.name is set
  git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name }}"

- name: git user.email is set
  git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email }}"
