- name: required packages are present
  become: yes
  apt:
    pkg:
      - python-is-python3
      - python3-pip
      - python3-virtualenv
    state: present

- name: "django is present"
  pip:
    name: "django"
