- name: required packages are present
  become: yes
  apt:
    pkg:
      - python-is-python3
      - python3-pip
    state: present

- name: "virtualenv is present"
  pip:
    name: "virtualenv"

- name: "django is present"
  pip:
    name: "django"
