- name: required packages are installed
  become: yes
  apt:
    pkg:
      - composer
      - php
      - php-bcmath
      - php-common
      - php-cli
      - php-curl
      - php-dev
      - php-gd
      - php-imap
      - php-intl
      - php-json
      - php-mbstring
      - php-mysql
      - php-xdebug
      - php-xml
      - php-zip
    state: present
  notify:
    - setup composer

- name: set default php config source
  set_fact:
    php_config_path: "example.php.ini"
  when: php_config_path is not defined # only if not custom php_config path

- name: php is configured
  become: yes
  copy:
    src: "{{ playbook_dir }}/config/{{ php_config_path }}"
    remote_src: no
    dest: "/etc/php/7.4/cli/php.ini"

- name: ufw 8000 is allowed
  become: yes
  ufw:
    rule: allow
    port: "8000"
    proto: tcp
  when: wsl_mode is not defined # skip when wsl_mode
  notify:
    - enable ufw
