- name: packages are up to date
  apt:
    upgrade: dist

- name: required packages are present
  apt:
    pkg:
      - git
      - htop
    state: present

- include_role:
    name: git

- name: set default ssh config source
  set_fact:
    termux_sshd_path: "example.termux_sshd"
  when: termux_sshd_path is not defined # only if not custom ssh_config path

- name: ssh server is configured
  copy:
    src: "{{ playbook_dir }}/config/{{ termux_sshd_path }}"
    remote_src: no
    dest: "$PREFIX/etc/ssh/sshd_config"
