- name: required packages are installed
  become: yes
  apt:
    pkg:
      - mysql-client
      - mysql-server
      - python3-pip
    state: present
  notify:
    - setup mysql

- name: mysql service is active
  become: yes
  service:
    name: mysql
    state: started

- name: set default mysql config source
  set_fact:
    mysql_config_path: "example.mysqld.cnf"
  when: mysql_config_path is not defined # only if not custom mysql_config path

- name: mysql server is configured
  become: yes
  copy:
    src: "{{ playbook_dir }}/config/{{ mysql_config_path }}"
    remote_src: no
    dest: "/etc/mysql/mysql.conf.d/mysqld.cnf"
  notify:
    - restart mysql

- name: pymysql pip module is present
  become: true
  pip:
    name: pymysql
    state: present
