- name: required packages are present
  become: yes
  apt:
    pkg:
      - docker
      - docker-compose
    state: present

- name: docker service is active
  become: yes
  service:
    name: docker
    state: started

- name: "group 'docker' is present"
  become: yes
  group:
    name: www
    state: present

- name: "'{{ ansible_user }}' is in 'docker' group"
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups: [docker]
    append: yes
