- name: packages are up to date
  become: yes
  apt:
    upgrade: dist

- name: required packages are present
  become: yes
  apt:
    pkg:
      - git
      - htop
      - ssh
      - tmux
    state: present

- name: set default ssh config source
  set_fact:
    sshd_config_path: "example.sshd_config"
  when: sshd_config_path is not defined # only if not custom ssh_config path

- name: ssh server is configured
  become: yes
  copy:
    src: "{{ playbook_dir }}/config/{{ sshd_config_path }}"
    remote_src: no
    dest: "/etc/ssh/sshd_config"
  notify:
    - restart ssh

- name: ssh server is active
  become: yes
  service:
    name: ssh
    state: started

- include_role:
    name: git

- name: ufw ssh firewall rule is limited
  become: yes
  ufw:
    rule: limit
    port: ssh
    proto: tcp
  when: wsl_mode is not defined # skip when wsl_mode

- name: ufw is enabled
  become: yes
  ufw:
    state: enabled
    policy: deny
  when: wsl_mode is not defined # skip when wsl_mode
